### ISSUE TITLE
staging site error re: alerts

### ISSUE THREAD

**Issue by thomastrillium** [trilliumtransit/mountaintransit#1]
Holly just pushed the live site to staging and a weird text error appeared at the top of the home page alerts:

> Warning: array_map(): Argument #2 should be an array in /nas/content/staging/mountainmarta/wp-content/themes/mountain/functions.php on line 433
> 
> Warning: join(): Invalid arguments passed in /nas/content/staging/mountainmarta/wp-content/plugins/custom-posts-plugin/api.php on line 353

Note, result was then to run an update on the live site. Live site is now correct. Staging is broken.

**Comment by NomeQ** [comment]
The error is showing up because no affected routes were chosen for the "New Mountain Transit Program" alert and it isn't able to get affected routes. This is just the debug settings running; it won't break anything on the live site (it's the exact same on the live site), the live site just hides all debug info. It's a useful debug error for staging and nothing more. 

Also a hint that it probably makes sense to check "all routes" as affected routes for this alert.
